FROM ubuntu:13.10

MAINTAINER Scarmod Team "ScarModContracts@Turner.com"

RUN apt-get update --fix-missing

#Install some packages we need
RUN apt-get install -y curl python-software-properties python g++ make software-properties-common build-essential libssl-dev wget

#make sure the package repository is up to date
RUN echo "deb http://archive.ubuntu.com/ubuntu precise main universe" > /etc/apt/sources.list
RUN apt-get update