
# Pull base image.
FROM dockerfile/java

MAINTAINER Scarmod Scheduling Team "ScarModScheduling@Turner.com"

# Install ElasticSearch.
RUN cd /opt && \
  wget https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-{{ES_Version}}.tar.gz && \
  tar -xvzf elasticsearch-{{ES_Version}}.tar.gz && \
  mv elasticsearch-{{ES_Version}} elasticsearch && \
  cd /usr/local/bin && \
  ln -s /opt/elasticsearch/bin/* . && \
  rm -f /opt/elasticsearch-{{ES_Version}}.tar.gz

# Define mountable directories.
VOLUME ["/data"]

# Define working directory.
WORKDIR /data

# Define default command.
CMD ["elasticsearch"]

# Expose ports.
#   - 9200: HTTP
#   - 9300: transport
EXPOSE 9200 9300
